name: Lint & Tests
on:
  - push
jobs:
  lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake lint
      - run: bundle exec rake rspec
